/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/activity': RouteRecordInfo<
      '/admin/activity',
      '/admin/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/jobs/': RouteRecordInfo<
      '/admin/jobs/',
      '/admin/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/jobs/[id]': RouteRecordInfo<
      '/admin/jobs/[id]',
      '/admin/jobs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register/': RouteRecordInfo<
      '/auth/register/',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register/candidate': RouteRecordInfo<
      '/auth/register/candidate',
      '/auth/register/candidate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register/employer': RouteRecordInfo<
      '/auth/register/employer',
      '/auth/register/employer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/': RouteRecordInfo<
      '/candidate/',
      '/candidate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/applications/': RouteRecordInfo<
      '/candidate/applications/',
      '/candidate/applications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/applications/[id]': RouteRecordInfo<
      '/candidate/applications/[id]',
      '/candidate/applications/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/candidate/jobs': RouteRecordInfo<
      '/candidate/jobs',
      '/candidate/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/profile': RouteRecordInfo<
      '/candidate/profile',
      '/candidate/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/resumes': RouteRecordInfo<
      '/candidate/resumes',
      '/candidate/resumes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/showcase': RouteRecordInfo<
      '/dev/showcase',
      '/dev/showcase',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employer/': RouteRecordInfo<
      '/employer/',
      '/employer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employer/applications/': RouteRecordInfo<
      '/employer/applications/',
      '/employer/applications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employer/applications/[id]': RouteRecordInfo<
      '/employer/applications/[id]',
      '/employer/applications/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/employer/company': RouteRecordInfo<
      '/employer/company',
      '/employer/company',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employer/jobs/': RouteRecordInfo<
      '/employer/jobs/',
      '/employer/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employer/jobs/[id]/': RouteRecordInfo<
      '/employer/jobs/[id]/',
      '/employer/jobs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/employer/jobs/[id]/edit': RouteRecordInfo<
      '/employer/jobs/[id]/edit',
      '/employer/jobs/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/employer/jobs/create': RouteRecordInfo<
      '/employer/jobs/create',
      '/employer/jobs/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forbidden': RouteRecordInfo<
      '/forbidden',
      '/forbidden',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/': RouteRecordInfo<
      '/jobs/',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/[id]': RouteRecordInfo<
      '/jobs/[id]',
      '/jobs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/unauthorized': RouteRecordInfo<
      '/unauthorized',
      '/unauthorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/admin/_parent.vue': {
      routes:
        | '/admin/'
        | '/admin/activity'
        | '/admin/jobs/'
        | '/admin/jobs/[id]'
      views:
        | 'default'
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/activity.vue': {
      routes:
        | '/admin/activity'
      views:
        | never
    }
    'src/pages/admin/jobs/index.vue': {
      routes:
        | '/admin/jobs/'
      views:
        | never
    }
    'src/pages/admin/jobs/[id].vue': {
      routes:
        | '/admin/jobs/[id]'
      views:
        | never
    }
    'src/pages/auth/_parent.vue': {
      routes:
        | '/auth/login'
        | '/auth/register/'
        | '/auth/register/candidate'
        | '/auth/register/employer'
      views:
        | 'default'
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/auth/register/index.vue': {
      routes:
        | '/auth/register/'
      views:
        | never
    }
    'src/pages/auth/register/candidate.vue': {
      routes:
        | '/auth/register/candidate'
      views:
        | never
    }
    'src/pages/auth/register/employer.vue': {
      routes:
        | '/auth/register/employer'
      views:
        | never
    }
    'src/pages/candidate/_parent.vue': {
      routes:
        | '/candidate/'
        | '/candidate/applications/'
        | '/candidate/applications/[id]'
        | '/candidate/jobs'
        | '/candidate/profile'
        | '/candidate/resumes'
      views:
        | 'default'
    }
    'src/pages/candidate/index.vue': {
      routes:
        | '/candidate/'
      views:
        | never
    }
    'src/pages/candidate/applications/index.vue': {
      routes:
        | '/candidate/applications/'
      views:
        | never
    }
    'src/pages/candidate/applications/[id].vue': {
      routes:
        | '/candidate/applications/[id]'
      views:
        | never
    }
    'src/pages/candidate/jobs.vue': {
      routes:
        | '/candidate/jobs'
      views:
        | never
    }
    'src/pages/candidate/profile.vue': {
      routes:
        | '/candidate/profile'
      views:
        | never
    }
    'src/pages/candidate/resumes.vue': {
      routes:
        | '/candidate/resumes'
      views:
        | never
    }
    'src/pages/dev/showcase.vue': {
      routes:
        | '/dev/showcase'
      views:
        | never
    }
    'src/pages/employer/_parent.vue': {
      routes:
        | '/employer/'
        | '/employer/applications/'
        | '/employer/applications/[id]'
        | '/employer/company'
        | '/employer/jobs/'
        | '/employer/jobs/[id]/'
        | '/employer/jobs/[id]/edit'
        | '/employer/jobs/create'
      views:
        | 'default'
    }
    'src/pages/employer/index.vue': {
      routes:
        | '/employer/'
      views:
        | never
    }
    'src/pages/employer/applications/index.vue': {
      routes:
        | '/employer/applications/'
      views:
        | never
    }
    'src/pages/employer/applications/[id].vue': {
      routes:
        | '/employer/applications/[id]'
      views:
        | never
    }
    'src/pages/employer/company.vue': {
      routes:
        | '/employer/company'
      views:
        | never
    }
    'src/pages/employer/jobs/index.vue': {
      routes:
        | '/employer/jobs/'
      views:
        | never
    }
    'src/pages/employer/jobs/[id]/index.vue': {
      routes:
        | '/employer/jobs/[id]/'
      views:
        | never
    }
    'src/pages/employer/jobs/[id]/edit.vue': {
      routes:
        | '/employer/jobs/[id]/edit'
      views:
        | never
    }
    'src/pages/employer/jobs/create.vue': {
      routes:
        | '/employer/jobs/create'
      views:
        | never
    }
    'src/pages/forbidden.vue': {
      routes:
        | '/forbidden'
      views:
        | never
    }
    'src/pages/jobs/index.vue': {
      routes:
        | '/jobs/'
      views:
        | never
    }
    'src/pages/jobs/[id].vue': {
      routes:
        | '/jobs/[id]'
      views:
        | never
    }
    'src/pages/unauthorized.vue': {
      routes:
        | '/unauthorized'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
