/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/candidate/': RouteRecordInfo<
      '/candidate/',
      '/candidate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employer/': RouteRecordInfo<
      '/employer/',
      '/employer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/employer/applications': RouteRecordInfo<
      '/employer/applications',
      '/employer/applications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/': RouteRecordInfo<
      '/jobs/',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/[id]': RouteRecordInfo<
      '/jobs/[id]',
      '/jobs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/_parent.vue': {
      routes:
        | '/admin/'
      views:
        | 'default'
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/auth/_parent.vue': {
      routes:
        | '/auth/login'
        | '/auth/register'
      views:
        | 'default'
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
    }
    'src/pages/candidate/_parent.vue': {
      routes:
        | '/candidate/'
      views:
        | 'default'
    }
    'src/pages/candidate/index.vue': {
      routes:
        | '/candidate/'
      views:
        | never
    }
    'src/pages/employer/_parent.vue': {
      routes:
        | '/employer/'
        | '/employer/applications'
      views:
        | 'default'
    }
    'src/pages/employer/index.vue': {
      routes:
        | '/employer/'
      views:
        | never
    }
    'src/pages/employer/applications.vue': {
      routes:
        | '/employer/applications'
      views:
        | never
    }
    'src/pages/jobs/index.vue': {
      routes:
        | '/jobs/'
      views:
        | never
    }
    'src/pages/jobs/[id].vue': {
      routes:
        | '/jobs/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
